resources:
- namespace.yaml
- ../../manifests/mysql/overlays/qa
- ../../manifests/insultgenerator/overlays/qa

patches:
  - patch: |-
      - op: replace
        path: "/metadata/namespace"
        value: "insult-qa"
    target:
      name: .*
