apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: quarkify
stringData:
  database-name: sampledb
  database-password: passwd
  database-root-password: passwd
  database-user: sampleuser